/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Time = IDL.Int;
export const SlotId = IDL.Text;
export const SlotStatus = IDL.Variant({
  'booked' : IDL.Null,
  'available' : IDL.Null,
});
export const BookerDetails = IDL.Record({
  'name' : IDL.Text,
  'phone' : IDL.Text,
});
export const BookingSlot = IDL.Record({
  'id' : SlotId,
  'startTime' : Time,
  'status' : SlotStatus,
  'endTime' : Time,
  'date' : Time,
  'bookerDetails' : IDL.Opt(BookerDetails),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addSlot' : IDL.Func([Time, Time, Time], [SlotId], []),
  'bookSlot' : IDL.Func([SlotId, IDL.Text, IDL.Text], [], []),
  'cancelBooking' : IDL.Func([SlotId], [], []),
  'deleteSlot' : IDL.Func([SlotId], [], []),
  'getAllSlots' : IDL.Func([], [IDL.Vec(BookingSlot)], ['query']),
  'getAvailableSlots' : IDL.Func([], [IDL.Vec(BookingSlot)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Time = IDL.Int;
  const SlotId = IDL.Text;
  const SlotStatus = IDL.Variant({
    'booked' : IDL.Null,
    'available' : IDL.Null,
  });
  const BookerDetails = IDL.Record({ 'name' : IDL.Text, 'phone' : IDL.Text });
  const BookingSlot = IDL.Record({
    'id' : SlotId,
    'startTime' : Time,
    'status' : SlotStatus,
    'endTime' : Time,
    'date' : Time,
    'bookerDetails' : IDL.Opt(BookerDetails),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addSlot' : IDL.Func([Time, Time, Time], [SlotId], []),
    'bookSlot' : IDL.Func([SlotId, IDL.Text, IDL.Text], [], []),
    'cancelBooking' : IDL.Func([SlotId], [], []),
    'deleteSlot' : IDL.Func([SlotId], [], []),
    'getAllSlots' : IDL.Func([], [IDL.Vec(BookingSlot)], ['query']),
    'getAvailableSlots' : IDL.Func([], [IDL.Vec(BookingSlot)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };